Repository imiphp/imi, pull requests merged in 2021-11, with the labels that each got.

#201 修复权限组件非静态的问题
  src/Components/access-control/src/AccessControl/Operation.php
Labels: bug

#209 📃 docs:
  doc/components/websocketServer/group.md
Labels: document

#206 解决 php 8.1 兼容问题
  .github/docker-compose.yml
  .github/prepare-kafka.sh
  .github/workflows/ci-php-81.yml
  .github/workflows/ci.yml
  src/Bean/Annotation/Base.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Statement.php
  src/Components/pgsql/tests/config/config.php
  src/Components/queue/src/Model/QueueStatus.php
  src/Components/swoole/src/Db/Driver/Swoole/Statement.php
  src/Db/Mysql/Drivers/Mysqli/Statement.php
  src/Db/Mysql/Drivers/PdoMysql/Statement.php
  src/Db/Query/PaginateResult.php
  src/Model/BaseModel.php
  src/Server/Http/SuperGlobals/Cookie.php
  src/Server/Http/SuperGlobals/Files.php
  src/Server/Http/SuperGlobals/Get.php
  src/Server/Http/SuperGlobals/Post.php
  src/Server/Http/SuperGlobals/Request.php
  src/Server/Http/SuperGlobals/Server.php
  src/Server/Http/SuperGlobals/Session.php
  src/Util/ArrayData.php
  src/Util/ArrayList.php
  src/Util/FilterableList.php
  src/Util/LazyArrayObject.php
  src/Util/StaticValueStorage.php
  src/Util/Traits/TBeanRealClass.php
  tests/unit/Component/PHPUnitHook.php
Labels: optimization
