Repository imiphp/imi, pull requests merged in 2021-09, with the labels that each got.

#139 改进连接池空闲回收：仅当前资源大于最小资源下才触发
  src/Pool/BasePool.php
Labels: optimization

#149 修复定时任务锁参数类型错误
  src/Cron/CronLock.php
Labels: bug

#150 定时任务进程支持终端回显
  doc/components/task/cron.md
  src/Components/swoole/src/Cron/CronManager.php
  src/Components/swoole/src/Process/ProcessManager.php
  src/functions.php
Labels: enhancement

#146 修复软删除默认值为null，查询出错
  src/Model/SoftDelete/Traits/TSoftDelete.php
Labels: bug

#151 修复 PolymorphicToOne 注解的 insert、update、delete 关联操作
  src/Model/ModelRelationManager.php
  src/Model/Relation/Delete.php
  src/Model/Relation/Insert.php
  src/Model/Relation/Query.php
  src/Model/Relation/Update.php
Labels: bug

#163 修复更新权限文档中注释说明
  doc/components/access-control.md
  src/Components/access-control/src/Model/Base/MemberOperationRelationBase.php
Labels: bug, document
