Repository imiphp/imi, pull requests merged in 2021-08, with the labels that each got.

#111 修正关于视图注解的使用方法
  doc/components/httpserver/view.md
  src/Components/workerman-gateway/tests/unit/AppServer/Tests/WebSocket/Workerman/ServerUtilTest.php
  src/Components/workerman/tests/unit/ChannelServerUtilServer/Tests/WebSocket/ServerUtilTest.php
Labels: document, optimization

#114 调整AOP介绍相关内容
  doc/components/aop/index.md
  doc/components/httpserver/aop.md
Labels: document

#138 连接池支持按照最大空闲时间对资源执行Gc
  .php-cs-fixer.php
  doc/components/db/index.md
  doc/components/pool/index.md
  doc/components/redis/index.md
  src/Pool/BasePool.php
  src/Pool/Interfaces/IPoolConfig.php
  src/Pool/PoolConfig.php
Labels: enhancement
