Repository imiphp/imi, pull requests merged in 2022-07, with the labels that each got.

#365 容器增加3个方法：set、newInstance、bindCallable
  doc/base/version/2.0-2.1.md
  doc/core/container.md
  src/App.php
  src/Bean/Container.php
  src/Cache/CacheManager.php
  src/Components/amqp/src/Pool/AMQPPool.php
  src/Components/queue/src/Process/SwooleQueueConsumerProcess.php
  src/Components/queue/src/Process/WorkermanQueueWorkerProcess.php
  src/Components/queue/src/Service/QueueService.php
  src/Components/queue/tests/Queue/RedisQueueTest.php
  src/Components/roadrunner/src/HotUpdate/HotUpdateProcess.php
  src/Components/swoole/src/Db/Pool/CoroutineDbPool.php
  src/Components/swoole/src/HotUpdate/HotUpdateProcess.php
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/swoole/src/Process/ProcessPoolManager.php
  src/Components/workerman/src/HotUpdate/HotUpdateProcess.php
  src/Components/workerman/src/Process/ProcessManager.php
  src/Db/Db.php
  src/Db/Pool/SyncDbPool.php
  src/Lock/Aop/TLockableParser.php
  src/Lock/Lock.php
  src/Model/Model.php
  src/RequestContext.php
  src/Server/Group/TServerGroup.php
  src/Server/ServerManager.php
  tests/unit/Component/Tests/BeanTest.php
Labels: enhancement, 2.1

#371 Db 分块查询增强
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  src/Db/Query/Result.php
  src/Db/Query/Result/BaseChunkResult.php
  src/Db/Query/Result/ChunkByOffsetResult.php
  src/Db/Query/Result/ChunkResult.php
  src/Db/Query/Result/CursorResult.php
  src/Db/Query/Result/TResultEntityCreate.php
  src/Model/Traits/TModelQuery.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#373 修复 bindColumn、bindParam
  src/Components/pgsql/src/Db/Drivers/PdoPgsql/Statement.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Statement.php
  src/Components/pgsql/src/Db/Drivers/SwooleNew/Statement.php
  src/Components/swoole/src/Db/Driver/Swoole/Statement.php
  src/Db/Interfaces/IStatement.php
  src/Db/Mysql/Drivers/Mysqli/Statement.php
  src/Db/Mysql/Drivers/PdoMysql/Statement.php
Labels: bug, 2.1, 2.0

#372 上下文添加方法：remember、unset
  doc/SUMMARY.md
  doc/base/version/2.0-2.1.md
  doc/components/websocketServer/session.md
  doc/core/container.md
  doc/core/requestContext.md
  src/Components/swoole/tests/unit/WebSocketServer/MainServer/Controller/Test2Controller.php
  src/Components/swoole/tests/unit/WebSocketServer/Tests/WSTest.php
  src/ConnectionContext.php
  src/RequestContext.php
  tests/unit/Component/Tests/RequestContextTest.php
Labels: enhancement, 2.1

#374 补充 Query::chunkEach 弃用记录
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
Labels: optimization, 2.1

#375 智能跳过一些无意义测试、更新文档
  .github/workflows/ci.yml
  .github/workflows/markdownlint.yml
  .github/workflows/phpcs.yml
  .github/workflows/phpstan.yml
  .github/workflows/rector.yml
  doc/SUMMARY.md
  doc/base/version/support.md
  doc/components/mq/amqp.md
  doc/components/mq/kafka.md
  doc/components/mq/redis.md
  src/Components/amqp/README.md
  src/Components/amqp/composer.json
  src/Components/apidoc/composer.json
  src/Components/kafka/README.md
  src/Components/kafka/composer.json
  src/Components/mqtt/composer.json
  src/Components/queue/composer.json
Labels: document, optimization, 2.1

#376 修复 AMQP 消息队列模式 ack
  src/Components/amqp/src/Base/BaseConsumer.php
  src/Components/amqp/src/Queue/AMQPQueueDriver.php
  src/Components/queue/src/Partial/SwooleBaseQueueConsumerPartial.php
Labels: bug, 2.1, 2.0

#377 getConnectionCount 设置为静态函数
  src/Server/Server.php
Labels: bug, 2.1, 2.0

#378 添加方法 Db::debugSql
  doc/base/version/2.0-2.1.md
  doc/components/db/index.md
  src/Db/Db.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
Labels: enhancement, 2.1

#383 重构 Process::isTtySupported()
  src/Util/Process.php
Labels: optimization, 2.1

#386 修复Jwt签名者为Ecdsa时，无法创建签名对象的错误；
  src/Components/jwt/src/Model/JWTConfig.php
Labels: bug, 2.1, 2.0

#387 修复 Server、Workerman ServerUtil 相关
  doc/utils/Server.md
  src/Components/swoole/src/Server/Util/LocalServerUtil.php
  src/Components/workerman-gateway/src/Swoole/Server/Util/GatewayServerUtil.php
  src/Components/workerman-gateway/src/Workerman/Server/Util/GatewayServerUtil.php
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Base.php
  src/Components/workerman/src/Server/Util/ChannelServerUtil.php
  src/Components/workerman/src/Server/Util/LocalServerUtil.php
  src/Server/Server.php
Labels: bug, 2.1, 2.0

#388 修复进程一直占用某个连接时，连接池心跳机制会开启越来越多的协程导致内存泄漏
  src/Components/swoole/src/Pool/BaseAsyncPool.php
Labels: bug, 2.1, 2.0

#394 fix<config>:修复httpApi调用rpc服务时启动项目重名报错问题
  src/Components/grpc/README.md
  src/Components/grpc/example/config/config.php
Labels: document

#393 Update grpc.md
  doc/components/rpc/grpc.md
Labels: document

#397 修复 kill php-fpm 的 fpm/start 命令有进程残留的问题
  src/Components/fpm/src/Server/Cli/Server.php
  src/Components/fpm/tests/HttpServer/bin/stop.sh
Labels: bug, 2.1, 2.0

#395 修复 Swoole 进程池的子进程崩溃无法重新拉起
  src/Components/swoole/src/Process/Pool.php
Labels: bug, 2.1
