Repository imiphp/imi, pull requests merged in 2022-10, with the labels that each got.

#444 移除消息队列消息类中未使用的 retryCount、maxRetryCount
  src/Components/queue/src/Contract/IMessage.php
  src/Components/queue/src/Model/Message.php
Labels: bug, 2.1

#445 增强 Column 注解的 createTime、updateTime 支持传入 int 值，表示时间精度，仅 bigint、int8 有效
  doc/components/orm/RDModel/definition.md
  src/Components/pgsql/src/Model/PgModel.php
  src/Model/Annotation/Column.php
  src/Model/Model.php
  tests/unit/Component/Model/Base/CreateTimeBase.php
  tests/unit/Component/Model/Base/UpdateTimeBase.php
  tests/unit/Component/Model/CreateTime.php
  tests/unit/Component/Model/UpdateTime.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#447 修复模型和数据库查询结果对象的 getArray() 方法，传 $className 时的兼容性
  src/Db/Query/Result.php
  src/Model/ModelQueryResult.php
  tests/unit/Component/Partial/Partial/TPartialClassA1.php
  tests/unit/Component/Partial/Partial/TPartialClassA2.php
Labels: bug, 2.1

#448 对 int、float、bool 类型配置参数值进行类型转换
  src/Components/amqp/src/Pool/AMQPCoroutinePool.php
  src/Components/amqp/src/Pool/AMQPPool.php
  src/Components/amqp/src/Pool/AMQPSyncPool.php
  src/Components/grpc/src/Client/GrpcClient.php
  src/Components/hprose/src/Imi-Server-Hprose/Server.php
  src/Components/mqtt/src/Client/MQTTClient.php
  src/Components/swoole/src/Db/Driver/Swoole/Driver.php
  src/Components/swoole/src/Server/Base.php
  src/Components/swoole/src/Server/Http/Server.php
  src/Components/swoole/src/Server/TcpServer/Server.php
  src/Components/swoole/src/Server/UdpServer/Server.php
  src/Components/swoole/src/Server/WebSocket/Server.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/TcpBusinessServer.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/WebSocketBusinessServer.php
  src/Components/workerman/src/Server/Channel/Server.php
  src/Db/Mysql/Drivers/Mysqli/Driver.php
  src/Redis/RedisManager.php
  src/Redis/Traits/TRedisPool.php
Labels: optimization, 2.1

#451 修复 Workerman 守护进程模式运行，记录日志导致进程退出重启
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Base.php
  src/Log/Logger.php
Labels: bug, 2.1, 2.0

#450 支持 AOP 切入带有引用返回值的方法
  doc/annotations/annotation.md
  doc/components/aop/index.md
  doc/components/httpserver/aop.md
  src/Aop/AroundJoinPoint.php
  src/Bean/BeanFactory.php
  src/Bean/BeanProxy.php
  src/Bean/ReflectionUtil.php
  src/Util/DelayBeanCallable.php
  src/Util/DelayClassCallable.php
  src/Util/DelayServerBeanCallable.php
  tests/phpunit.xml
  tests/unit/Component/Bean/ReferenceBean.php
  tests/unit/Component/Bean/ReferenceBeanAspect.php
  tests/unit/Component/Tests/BeanTest.php
  tests/unit/Component/config/config.php
Labels: enhancement, 2.1

#452 修复请求上下文销毁（php-fpm、roadrunner）及事件触发（非 Swoole）
  src/Components/roadrunner/src/Server/Http/Server.php
  src/Core/Context/DefaultContextManager.php
Labels: bug, 2.1, 2.0
