Repository imiphp/imi, pull requests merged in 2022-05, with the labels that each got.

#333 [ORM] 改进json类型字段，传入`null`时不要转换为`null`字符串
  src/Model/Model.php
  tests/unit/Component/Tests/ModelTest.php
Labels: optimization, 2.1

#334 在 Model 中支持 MySQL set 数据类型
  doc/base/version/2.0-2.1.md
  src/Model/Cli/Model/ModelGenerate.php
  src/Model/Model.php
  tests/phpunit.xml
  tests/unit/Component/Model/Base/TBase.php
  tests/unit/Component/Model/Base/TestBase.php
  tests/unit/Component/Model/Base/TestEnumBase.php
  tests/unit/Component/Model/Base/TestSetBase.php
  tests/unit/Component/Model/TestEnum.php
  tests/unit/Component/Model/TestSet.php
  tests/unit/Component/PHPUnitHook.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#335 修复 Swoole PgSql 部分场景无法断线重连
  src/Components/pgsql/src/Db/Contract/IPgsqlDb.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Driver.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Statement.php
  src/Components/pgsql/src/Db/PgsqlBase.php
Labels: bug, 2.1, 2.0

#338 为支持重复出现的注解类增加：Attribute::IS_REPEATABLE
  src/Aop/Annotation/FilterArg.php
  src/Aop/Annotation/InjectArg.php
  src/Bean/Annotation/Bean.php
  src/Bean/Annotation/ClassEventListener.php
  src/Bean/Annotation/Listener.php
  src/Bean/Annotation/Partial.php
  src/Cli/Annotation/Arg.php
  src/Cli/Annotation/Argument.php
  src/Cli/Annotation/Command.php
  src/Cli/Annotation/CommandAction.php
  src/Cli/Annotation/Operation.php
  src/Cli/Annotation/Option.php
  src/Cli/Annotation/Tool.php
  src/Components/amqp/src/Annotation/Exchange.php
  src/Components/amqp/src/Annotation/Queue.php
  src/Components/swoole/src/Process/Annotation/Process.php
  src/Components/swoole/src/Process/Annotation/ProcessPool.php
  src/Components/swoole/src/Task/Annotation/Task.php
  src/Components/workerman/src/Process/Annotation/Process.php
  src/Cron/Annotation/Cron.php
  src/HttpValidate/Annotation/ExtractData.php
  src/Lock/Annotation/Lockable.php
  src/Model/Annotation/ExtractProperty.php
  src/Model/Annotation/Relation/PolymorphicManyToMany.php
  src/Model/Annotation/Relation/PolymorphicOneToMany.php
  src/Model/Annotation/Relation/PolymorphicOneToOne.php
  src/Model/Annotation/Relation/PolymorphicToMany.php
  src/Model/Annotation/Relation/PolymorphicToOne.php
  src/Server/Http/Annotation/ExtractData.php
  src/Server/Http/Route/Annotation/Controller.php
  src/Server/Http/Route/Annotation/Middleware.php
  src/Server/Http/Route/Annotation/Route.php
  src/Server/TcpServer/Route/Annotation/TcpController.php
  src/Server/TcpServer/Route/Annotation/TcpMiddleware.php
  src/Server/TcpServer/Route/Annotation/TcpRoute.php
  src/Server/UdpServer/Route/Annotation/UdpController.php
  src/Server/UdpServer/Route/Annotation/UdpMiddleware.php
  src/Server/UdpServer/Route/Annotation/UdpRoute.php
  src/Server/WebSocket/Route/Annotation/WSController.php
  src/Server/WebSocket/Route/Annotation/WSMiddleware.php
  src/Server/WebSocket/Route/Annotation/WSRoute.php
  src/Tool/Annotation/Arg.php
  src/Tool/Annotation/Operation.php
  src/Tool/Annotation/Tool.php
  src/Validate/Annotation/Compare.php
  src/Validate/Annotation/Condition.php
  src/Validate/Annotation/Decimal.php
  src/Validate/Annotation/InEnum.php
  src/Validate/Annotation/InList.php
  src/Validate/Annotation/Integer.php
  src/Validate/Annotation/Number.php
  src/Validate/Annotation/Regex.php
  src/Validate/Annotation/Required.php
  src/Validate/Annotation/Text.php
Labels: bug, 2.1, 2.0

#339 修复 Swoole 服务器事件类型声明
  src/Components/swoole/src/Server/WebSocket/Server.php
Labels: bug, 2.1, 2.0

#341 修复 Swoole PgSql Statement 释放预处理语句
  src/Components/pgsql/src/Db/Drivers/Swoole/Driver.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Statement.php
Labels: bug, 2.1, 2.0

#342 更正文档案例符号
  doc/components/struct/atomic.md
Labels: document

#345 修复特定情况下 Result->isSuccess() 结果不正确
  src/Components/pgsql/src/Db/Drivers/PdoPgsql/Driver.php
  src/Components/pgsql/src/Db/Drivers/PdoPgsql/Statement.php
  src/Db/Db.php
  src/Db/Mysql/Drivers/PdoMysql/Driver.php
  src/Db/Mysql/Drivers/PdoMysql/Statement.php
  src/Db/Query/Query.php
  src/Db/Query/Result.php
Labels: bug, 2.1, 2.0

#343 修复 ProcessPool 和消息队列消费者
  doc/base/version/2.0-2.1.md
  doc/components/process-pool/imi.md
  src/Components/amqp/src/Base/BaseConsumer.php
  src/Components/queue/src/Partial/SwooleBaseQueueConsumerPartial.php
  src/Components/queue/src/Process/SwooleQueueConsumerProcess.php
  src/Components/swoole/src/Process/Pool.php
Labels: bug, 2.1, 2.0

#346 修复自定义进程 runtime
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/workerman/src/Process/ProcessManager.php
Labels: bug, 2.1, 2.0

#347 修复一些数据库和连接池问题
  src/Components/pgsql/src/Db/Drivers/PdoPgsql/Driver.php
  src/Components/pgsql/src/Db/Drivers/Swoole/Driver.php
  src/Components/swoole/src/Db/Driver/Swoole/Driver.php
  src/Db/Aop/TransactionAop.php
  src/Db/Db.php
  src/Db/Pool/DbResource.php
  src/Pool/Interfaces/IPoolConfig.php
  src/Pool/PoolConfig.php
  src/Pool/PoolManager.php
Labels: bug, 2.1, 2.0
