Repository imiphp/imi, pull requests merged in 2022-02, with the labels that each got.

#261 修复 whereBrackets() 返回一个 Where 对象时值绑定无效
  src/Db/Query/Where/WhereBrackets.php
Labels: bug, 2.1, 2.0

#262 模型注解 JsonEncode 增强，增加 JsonDecode 注解
  doc/components/orm/RDModel.md
  src/Model/Annotation/JsonDecode.php
  src/Model/Annotation/JsonEncode.php
  src/Model/BaseModel.php
  src/Model/Meta.php
  src/Model/Model.php
Labels: enhancement, 2.1

#265 新增环境变量 IMI_MACRO_LOCK_FILE_DIR 以支持在共享目录等不支持文件锁的文件系统中运行
  doc/base/config.md
  doc/base/qa.md
  src/Components/macro/src/AutoLoader.php
Labels: enhancement, 2.1

#264 新增 Model::exists() 用于判断记录是否存在
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  src/Components/pgsql/src/Db/Query/PgsqlQuery.php
  src/Components/pgsql/tests/Unit/Model/ModelTest.php
  src/Db/Mysql/Query/MysqlQuery.php
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  src/Model/Model.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#266 重构优化一些代码
  .github/actions/ci-prepare/action.yml
  .github/workflows/ci.yml
  .github/workflows/phpstan.yml
  .github/workflows/rector.yml
  doc/SUMMARY.md
  doc/base/version/1-2.md
  doc/base/version/2.0-2.1.md
  doc/components/db/index.md
  phpstan.neon
  src/Aop/AopAnnotationLoader.php
  src/Bean/Annotation/AnnotationManager.php
  src/Bean/BeanProxy.php
  src/Cache/Aop/CacheableAop.php
  src/Cli/ImiCommand.php
  src/Components/amqp/src/Base/Traits/TAMQP.php
  src/Components/amqp/src/Queue/QueueConsumer.php
  src/Components/amqp/src/Queue/QueuePublisher.php
  src/Components/amqp/src/Queue/SwooleQueueConsumer.php
  src/Components/amqp/src/Swoole/AMQPSwooleConnection.php
  src/Components/apidoc/src/Tool/DocTool.php
  src/Components/jwt/src/Aop/JWTValidationAop.php
  src/Components/kafka/src/Base/BaseConsumer.php
  src/Components/rate-limit/src/Aspect/RateLimitAspect.php
  src/Components/rate-limit/src/Aspect/WorkerLimitAspect.php
  src/Components/rpc/src/Listener/RouteInit.php
  src/Components/swoole/src/Cron/CronManager.php
  src/Components/swoole/src/Process/Pool.php
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/swoole/src/Server/Base.php
  src/Components/swoole/src/Util/Imi.php
  src/Db/Aop/TransactionAop.php
  src/Db/Query/Interfaces/IField.php
  src/Env.php
  src/Facade/BaseFacade.php
  src/Lock/Aop/LockAop.php
  src/Model/BaseModel.php
  src/Model/Cli/Table/TableGenerate.php
  src/Model/Meta.php
  src/Model/Model.php
  src/Model/ModelManager.php
  src/Model/RedisModel.php
  src/Model/Relation/Delete.php
  src/Model/Relation/Insert.php
  src/Model/Relation/Query.php
  src/Model/Relation/Struct/ManyToMany.php
  src/Model/Relation/Struct/PolymorphicManyToMany.php
  src/Model/Relation/Struct/TLeftAndRight.php
  src/Model/Relation/Update.php
  src/Model/SoftDelete/Traits/TSoftDelete.php
  src/Pool/Aop/PoolCleanAop.php
  src/RequestContextProxy/BaseRequestContextProxy.php
  src/Server/Http/Listener/HttpRouteInit.php
  src/Server/TcpServer/Listener/TcpRouteInit.php
  src/Server/UdpServer/Listener/UdpRouteInit.php
  src/Server/View/Parser/ViewParser.php
  src/Server/WebSocket/Listener/WSRouteInit.php
  src/Util/File.php
  src/Util/Imi.php
Labels: optimization, 2.1

#274 修复 whereBrackets 空数组时错误
  src/Db/Query/Where/WhereBrackets.php
Labels: bug, 2.1, 2.0

#273 添加 Where::raw 方法
  doc/components/db/index.md
  src/Db/Query/Where/Where.php
Labels: enhancement, 2.1

#275 枚举类增加 validate() 和 assert()
  doc/base/version/2.0-2.1.md
  doc/components/struct/enum.md
  src/Enum/BaseEnum.php
  tests/unit/Component/Tests/EnumTest.php
Labels: enhancement, 2.1

#277 Query->where() 条件的值支持传原始 SQL
  doc/base/version/2.0-2.1.md
  doc/components/db/index.md
  src/Db/Query/Where/Where.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
Labels: enhancement, 2.1

#279 修复 PHP 8.1 兼容
  src/Components/rate-limit/src/Annotation/BlockingConsumer.php
Labels: bug, 2.1, 2.0

#278 修复命令行参数默认值被强制类型转换
  src/Cli/ImiCommand.php
Labels: bug, 2.1, 2.0

#281 移除 Swoole 短名称检查检查，不启用也可以使用 imi
  src/Components/swoole/composer.json
  src/Components/swoole/src/SwooleApp.php
  src/Components/swoole/src/functions.php
Labels: optimization, 2.1, 2.0

#282 优化代码
  src/Bean/Parser/BeanParser.php
  src/Cli/ImiCommand.php
  src/Components/apidoc/src/Tool/DocTool.php
  src/Components/grpc/src/grpc/Util/GrpcInterfaceManager.php
  src/Db/Query/Query.php
  src/Pool/BaseSyncPool.php
  src/Util/DocBlock.php
Labels: optimization, 2.1

#285 修复模型 save() 处理自动填入创建时间
  src/Model/Model.php
  tests/unit/Component/Tests/ModelTest.php
Labels: bug, 2.1

#284 修复存在多个空 WhereBrackets 时构建错误
  src/Db/Query/Builder/BaseBuilder.php
Labels: bug, 2.1, 2.0

#283 修复 Async 中 SwooleResult->get() 不会层层获取最终结果
  src/Async/AsyncResult.php
  src/Components/swoole/src/Async/SwooleResult.php
Labels: bug, 2.1, 2.0

#286 修复 Workerman Gateway worker 中，WebSocket 连接事件处理抛出异常不会断开连接的问题
  src/Components/workerman-gateway/src/Swoole/Server/Business/Task/WorkerTask.php
  src/Components/workerman-gateway/src/Workerman/Server/Business/WebSocketBusinessServer.php
Labels: bug, 2.1, 2.0

#287 修复 Http 路由忽略大小写
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Controller/IndexController.php
  src/Components/swoole/tests/unit/HttpServer/Tests/RequestTest.php
  src/Server/Http/Route/HttpRoute.php
Labels: bug, 2.1, 2.0

#289 Grpc 功能改进和修复
  src/Components/grpc/src/grpc/Client/GrpcClient.php
  src/Components/grpc/src/grpc/Middleware/ActionMiddleware.php
  src/Components/grpc/src/server/Error/DefaultGrpcErrorHandler.php
  src/Components/hprose/src/Client/HproseSocketClient.php
  src/Components/rpc/src/Client/IRpcClient.php
  src/Components/rpc/src/Client/Pool/RpcClientResource.php
Labels: bug, enhancement, 2.1, 2.0
