Repository imiphp/imi, pull requests merged in 2022-03, with the labels that each got.

#290 支持定义命令行名称分割符
  doc/dev/tool.md
  src/Cli/Annotation/Command.php
  src/Cli/CliApp.php
  src/Cli/CliManager.php
  src/Cli/ImiCommand.php
  src/Cli/Parser/ToolParser.php
Labels: enhancement, 2.1

#288 [dev] Phar 支持
  .gitignore
  doc/SUMMARY.md
  doc/base/version/2.0-2.1.md
  doc/components/phar/index.md
  doc/core/consts.md
  split-repository/release.php
  split-repository/split.php
  src/App.php
  src/Cli/CliApp.php
  src/Components/macro/src/AutoLoader.php
  src/Components/phar/.gitignore
  src/Components/phar/bin/imi-phar
  src/Components/phar/composer.json
  src/Components/phar/config/imi-phar-cfg.php
  src/Components/phar/phar_init.php
  src/Components/phar/src/Constant.php
  src/Components/phar/src/Helper.php
  src/Components/phar/src/PharBuildCommand.php
  src/Components/phar/src/PharHandler.php
  src/Components/phar/src/PharService.php
  src/Core/App/Contract/BaseApp.php
  src/Util/Composer.php
  src/Util/File.php
  src/Util/Imi.php
  src/functions.php
Labels: enhancement, 2.1

#291 修复连接池资源被关闭后，释放连接时会重新加入连接池的问题
  .github/workflows/ci.yml
  src/Components/amqp/src/Pool/AMQPResource.php
  src/Components/kafka/src/Pool/KafkaResource.php
  src/Components/rpc/src/Client/Pool/RpcClientResource.php
  src/Components/shared-memory/src/Pool/ClientResource.php
  src/Components/swoole/src/Pool/BaseAsyncPool.php
  src/Db/Pool/DbResource.php
  src/Pool/BasePool.php
  src/Pool/BasePoolResource.php
  src/Pool/Interfaces/IPoolResource.php
  src/Redis/RedisResource.php
Labels: bug, 2.1, 2.0

#293 Phar 相关改进和废除不合理的常量
  doc/base/config.md
  doc/components/phar/index.md
  doc/core/consts.md
  src/App.php
  src/AppContexts.php
  src/Components/phar/config/imi-phar-cfg.php
  src/Components/phar/phar_init.php
  src/Components/phar/src/PharService.php
  src/Components/roadrunner/src/Server/Http/Server.php
  src/Core/App/Contract/BaseApp.php
  src/Util/Imi.php
  src/functions.php
Labels: bug, 2.1

#294 实现 WebSocket、Tcp、Udp 异常处理器
  doc/SUMMARY.md
  doc/components/httpserver/error.md
  doc/components/tcpServer/error.md
  doc/components/udpServer/error.md
  doc/components/websocketServer/error.md
  src/Components/swoole/src/Server/TcpServer/Server.php
  src/Components/swoole/src/Server/UdpServer/Server.php
  src/Components/swoole/src/Server/WebSocket/Server.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/Task/TcpWorkerTask.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/Task/WebSocketWorkerTask.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/Task/WorkerTask.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/TcpBusinessServer.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/WebSocketBusinessServer.php
  src/Components/workerman-gateway/src/Workerman/Server/Business/TcpBusinessServer.php
  src/Components/workerman-gateway/src/Workerman/Server/Business/WebSocketBusinessServer.php
  src/Components/workerman/src/Server/Tcp/Server.php
  src/Components/workerman/src/Server/Udp/Server.php
  src/Components/workerman/src/Server/WebSocket/Server.php
  src/Server/TcpServer/Error/ErrorHandler.php
  src/Server/TcpServer/Error/IErrorHandler.php
  src/Server/UdpServer/Error/ErrorHandler.php
  src/Server/UdpServer/Error/IErrorHandler.php
  src/Server/WebSocket/Error/ErrorHandler.php
  src/Server/WebSocket/Error/IErrorHandler.php
Labels: enhancement, 2.1

#295 修复连接池释放连接，可能导致下一次获取到正在使用的连接
  src/Components/swoole/src/Pool/PoolItem.php
Labels: bug, 2.1, 2.0

#296 官网图片加载优化
  website/src/index.js
Labels: optimization

#299 Async 中抛出异常，如果没有获取结果时，默认记录日志
  src/Async/Aop/AsyncAop.php
  src/Async/AsyncResult.php
  src/Components/swoole/src/Async/SwooleResult.php
  src/Components/swoole/tests/unit/Component/Tests/AsyncTest.php
  tests/unit/Component/Tests/AsyncTest.php
Labels: enhancement, 2.1

#301 支持在 imigo()、Imi\Swoole\Util\Coroutine::create() 中捕获异常并记录日志
  .github/swoole.dockerfile
  .github/workflows/phpcs.yml
  .github/workflows/phpstan.yml
  .github/workflows/rector.yml
  composer.json
  dev/bootstrap.php
  dev/config/config.php
  dev/include.php
  phpstan-components.neon
  phpstan.neon
  split-repository/release.php
  src/Components/amqp/dev/Dev.php
  src/Components/amqp/example/Process/SwooleTestProcess.php
  src/Components/amqp/example/bin/imi-swoole
  src/Components/amqp/example/bin/imi-workerman
  src/Components/amqp/tests/Queue/BaseQueueTest.php
  src/Components/grpc/dev/Dev.php
  src/Components/grpc/example/bin/imi
  src/Components/hprose/dev/Dev.php
  src/Components/kafka/dev/Dev.php
  src/Components/kafka/example/Process/SwooleTestProcess.php
  src/Components/kafka/example/bin/imi-swoole
  src/Components/kafka/example/bin/imi-workerman
  src/Components/mqtt/dev/Dev.php
  src/Components/mqtt/example/bin/imi
  src/Components/mqtt/tests/MQTT/MQTTTest.php
  src/Components/pgsql/dev/Dev.php
  src/Components/queue/dev/Dev.php
  src/Components/queue/example/bin/imi-swoole
  src/Components/queue/example/bin/imi-workerman
  src/Components/queue/src/Process/SwooleQueueConsumerProcess.php
  src/Components/queue/tests/Queue/BaseQueueTest.php
  src/Components/smarty/dev/Dev.php
  src/Components/smarty/example/bin/imi
  src/Components/swoole-tracker/example/HttpServer/bin/imi
  src/Components/swoole-tracker/example/TCPServer/bin/imi
  src/Components/swoole-tracker/example/UDPServer/bin/imi
  src/Components/swoole-tracker/example/WebSocketServer/bin/imi
  src/Components/swoole/dev/Dev.php
  src/Components/swoole/src/Server/Util/LocalServerUtil.php
  src/Components/swoole/src/Server/Util/RedisServerUtil.php
  src/Components/swoole/src/functions.php
  src/Components/swoole/tests/unit/Component/Tests/CacheAnnotationTest.php
  src/Components/swoole/tests/unit/Component/Tests/LockAnnotationTest.php
  src/Components/workerman-gateway/dev/Dev.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/TcpBusinessServer.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/WebSocketBusinessServer.php
  src/Util/File.php
  src/Util/File/FileFinder.php
  src/functions.php
  tests/unit/Component/Tests/Util/RandomTest.php
Labels: enhancement, 2.1

#303 修复一些问题
  doc/components/mq/amqp.md
  doc/core/container.md
  src/Components/amqp/example/ApiServer/Controller/IndexController.php
  src/Components/amqp/src/Base/BasePublisher.php
  src/Components/amqp/src/Base/Traits/TAMQP.php
  src/Components/amqp/src/Pool/AMQPCoroutinePool.php
  src/Components/amqp/src/Pool/AMQPResource.php
  src/Components/grpc/src/grpc/Client/GrpcClient.php
  src/Components/rpc/src/Client/Pool/RpcClientResource.php
  src/Components/swoole/src/Listener/AfterWorkerStart.php
  src/Components/swoole/src/Server/Http/Server.php
  src/Components/swoole/src/Server/TcpServer/Server.php
  src/Components/swoole/src/Server/UdpServer/Server.php
  src/Components/swoole/src/Server/WebSocket/Server.php
  src/Worker.php
  tests/unit/Component/Bean/BeanNew.php
  tests/unit/Component/Tests/BeanTest.php
Labels: bug, 2.1, 2.0

#304 优化错误报告
  doc/base/config.md
  doc/core/handleError.md
  src/Components/swoole/src/Server/Base.php
  src/Log/ErrorLog.php
Labels: optimization, 2.1

#300 phar 改进
  .github/actions/ci-prepare/action.yml
  .github/workflows/ci.yml
  composer.json
  src/Components/phar/.gitattributes
  src/Components/phar/src/Constant.php
  src/Components/phar/src/PharBuildCommand.php
  src/Components/phar/tests/project/.env
  src/Components/phar/tests/project/.gitignore
  src/Components/phar/tests/project/.imi-phar-cfg.php
  src/Components/phar/tests/project/.rr.yaml
  src/Components/phar/tests/project/ApiServer/Controller/IndexController.php
  src/Components/phar/tests/project/ApiServer/Middleware/PoweredBy.php
  src/Components/phar/tests/project/ApiServer/config/config.php
  src/Components/phar/tests/project/composer.json
  src/Components/phar/tests/project/config/beans.php
  src/Components/phar/tests/project/config/config.php
  src/Components/phar/tests/project/init.php
  src/Components/phar/tests/run-tests.php
  src/Components/roadrunner/bootstrap.php
  src/Core/App/Contract/BaseApp.php
Labels: optimization, 2.1

#302 `Db`的分块查询与游标查询支持
  doc/SUMMARY.md
  doc/components/db/config.md
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  doc/components/orm/RDModel/definition.md
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Interfaces/IResult.php
  src/Db/Query/PaginateResult.php
  src/Db/Query/Query.php
  src/Db/Query/Result.php
  src/Db/Query/Result/ChunkResult.php
  src/Db/Query/Result/CursorResult.php
  src/Model/Traits/TModelQuery.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#309 更新文档
  doc/components/orm/RDModel/definition.md
Labels: document, 2.1
