Repository imiphp/imi, pull requests merged in 2022-04, with the labels that each got.

#308 支持单文件运行 imi
  doc/SUMMARY.md
  doc/base/version/2.0-2.1.md
  doc/core/events.md
  doc/core/quickStart.md
  src/App.php
  src/Components/amqp/tests/PHPUnitHook.php
  src/Components/amqp/tests/TestApp.php
  src/Components/grpc/tests/Grpc/PHPUnitHook.php
  src/Components/grpc/tests/Grpc/TestApp.php
  src/Components/jwt/tests/PHPUnitHook.php
  src/Components/jwt/tests/TestApp.php
  src/Components/kafka/tests/PHPUnitHook.php
  src/Components/kafka/tests/TestApp.php
  src/Components/mqtt/tests/PHPUnitHook.php
  src/Components/mqtt/tests/TestApp.php
  src/Components/pgsql/tests/PHPUnitHook.php
  src/Components/pgsql/tests/TestApp.php
  src/Components/queue/tests/PHPUnitHook.php
  src/Components/queue/tests/TestApp.php
  src/Components/snowflake/tests/PHPUnitHook.php
  src/Components/snowflake/tests/TestApp.php
  src/Components/swoole/src/Log/SwooleLogger.php
  src/Components/swoole/src/Pool/Listener/WorkerExit.php
  src/Components/swoole/tests/unit/Component/PHPUnitHook.php
  src/Components/swoole/tests/unit/Component/TestApp.php
  src/Components/swoole/tests/unit/Component/Tests/QuickStartTest.php
  src/Components/swoole/tests/unit/Component/composer.json
  src/Components/swoole/tests/unit/Component/test.php
  tests/unit/Component/PHPUnitHook.php
  tests/unit/Component/TestApp.php
  tests/unit/Component/Tests/AppTest.php
  tests/unit/Component/composer.json
  tests/unit/Component/test.php
Labels: enhancement, 2.1

#311 新增一个更加方便遍历分块查询的方法 chunkEach()
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  src/Model/Traits/TModelQuery.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#312 移除 imi-macro 强制依赖
  phpstan-components.neon
  src/Components/swoole/composer.json
  src/Components/swoole/src/Process/Process.php
  src/Components/swoole/src/Process/Process.php.macro
  src/Components/swoole/src/Util/Coroutine.php
  src/Components/swoole/src/Util/Coroutine.php.macro
  src/Components/swoole/src/Util/Coroutine.typed.php
Labels: optimization, 2.1

#313 支持验证器动态数组对象验证
  doc/components/validation/index.md
  src/Validate/Validator.php
  tests/phpunit.xml
  tests/unit/Component/Tests/ValidatorAnnotationTest.php
  tests/unit/Component/Validate/Classes/TestValidator.php
Labels: enhancement, 2.1

#314 Db 构建器添加 find, value, column 查询方法
  composer.json
  doc/components/db/index.md
  doc/components/orm/RDModel.md
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  tests/helper.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#315 新增服务启动时，输出注册到 imi 的组件信息
  src/Cli/CliApp.php
  src/Components/amqp/example/config/config.php
  src/Components/amqp/src/Pool/AMQPResource.php
  src/Components/amqp/tests/PHPUnitHook.php
  src/Components/grpc/src/grpc/Main.php
  src/Components/grpc/tests/Grpc/PHPUnitHook.php
  src/Components/kafka/tests/PHPUnitHook.php
  src/Components/mqtt/tests/PHPUnitHook.php
  src/Components/queue/tests/PHPUnitHook.php
  src/Components/swoole/composer.json
  src/Components/swoole/src/Context/CoroutineContextManager.php
  src/Pool/BasePool.php
Labels: enhancement, 2.1

#317 模型关联支持在查询结果中，包含被软删除的数据
  doc/base/version/2.0-2.1.md
  doc/components/orm/relation/index.md
  src/Model/Annotation/Relation/ManyToMany.php
  src/Model/Annotation/Relation/OneToMany.php
  src/Model/Annotation/Relation/OneToOne.php
  src/Model/Annotation/Relation/PolymorphicManyToMany.php
  src/Model/Annotation/Relation/PolymorphicOneToMany.php
  src/Model/Annotation/Relation/PolymorphicOneToOne.php
  src/Model/Annotation/Relation/PolymorphicToMany.php
  src/Model/Annotation/Relation/PolymorphicToOne.php
  src/Model/ModelRelationManager.php
  src/Model/Relation/Query.php
Labels: enhancement, 2.1

#319 修复启动服务后并发压测，概率出现响应内容为空
  src/Server/Http/Dispatcher.php
  src/Server/Http/Error/HttpNotFoundHandler.php
  src/Server/TcpServer/Dispatcher.php
  src/Server/UdpServer/Dispatcher.php
  src/Server/WebSocket/Dispatcher.php
Labels: bug, 2.1, 2.0

#322 修复 workerman-gateway Swoole worker 会在 task 进程中运行的问题
  src/Components/workerman-gateway/src/Swoole/Server/Business/TcpBusinessServer.php
  src/Components/workerman-gateway/src/Swoole/Server/Business/WebSocketBusinessServer.php
Labels: bug, 2.1, 2.0

#320 支持在 Swoole、Workerman 进程启动和停止时输出日志
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/swoole/src/Server/Base.php
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Base.php
  src/Components/workerman/src/Server/Cli/Server.php
  src/Components/workerman/src/Server/Contract/IWorkermanServer.php
Labels: enhancement, 2.1

#326 修复使用SwooleDB引擎之后报 参数数量不一致 的错误
  src/Components/swoole/src/Db/Driver/Swoole/Statement.php
Labels: bug, 2.1, 2.0

#323 修复无法移除手动增加的定时任务
  src/Components/swoole/src/Cron/CronManager.php
Labels: bug, 2.1, 2.0

#327 CronUtil 支持检测任务状态 和 获取所有激活任务列表
  doc/components/task/cron.md
  src/Components/swoole/src/Cron/CronManager.php
  src/Components/swoole/src/Cron/Process/CronProcess.php
  src/Cron/Client.php
  src/Cron/Contract/ICronManager.php
  src/Cron/CronManager.php
  src/Cron/Message/CommonMsg.php
  src/Cron/Message/GetRealTasks.php
  src/Cron/Message/GetTask.php
  src/Cron/Message/HasTask.php
  src/Cron/Util/CronUtil.php
Labels: enhancement, 2.1

#328 修复 Workerman 守护进程模式运行，记录日志导致进程退出重启
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Base.php
  src/Log/Handler/ConsoleHandler.php
  src/Log/Logger.php
Labels: bug, 2.1, 2.0

#325 优化 amqp
  src/Components/amqp/src/Base/BaseConsumer.php
  src/Components/amqp/src/Pool/AMQPResource.php
  src/Components/amqp/src/Queue/AMQPQueueDriverHandler.php
  src/Components/amqp/src/Queue/QueueConsumer.php
  src/Components/amqp/src/Queue/SwooleQueueConsumer.php
  src/Components/amqp/tests/PHPUnitHook.php
  src/Components/amqp/tests/Queue/BaseQueueTest.php
Labels: optimization, 2.1, 2.0

#329 优化创建 Swoole 子服务器
  src/Components/swoole/src/Server/Base.php
  src/Components/swoole/src/Server/Http/Server.php
  src/Components/swoole/src/Server/TcpServer/Server.php
  src/Components/swoole/src/Server/UdpServer/Server.php
  src/Components/swoole/src/Server/WebSocket/Server.php
Labels: optimization, 2.1

#330 修复进程启动和停止日志中的标签
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/swoole/src/Server/Base.php
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Base.php
Labels: bug, 2.1

#331 调整 Grpc 组件目录结构
  doc/components/rpc/grpc.md
  src/Components/grpc/composer.json
  src/Components/grpc/src/Client/Annotation/GrpcService.php
  src/Components/grpc/src/Client/Contract/IGrpcService.php
  src/Components/grpc/src/Client/GrpcClient.php
  src/Components/grpc/src/Client/GrpcService.php
  src/Components/grpc/src/Client/ServiceAgent.php
  src/Components/grpc/src/Enum/GrpcStatus.php
  src/Components/grpc/src/Listener/WorkerExit.php
  src/Components/grpc/src/Main.php
  src/Components/grpc/src/Middleware/ActionMiddleware.php
  src/Components/grpc/src/Parser.php
  src/Components/grpc/src/Server/Error/DefaultGrpcErrorHandler.php
  src/Components/grpc/src/Server/Error/GrpcErrorHandler.php
  src/Components/grpc/src/Server/Server.php
  src/Components/grpc/src/Util/GrpcInterfaceManager.php
  src/Components/grpc/src/config/config.php
  src/Components/grpc/src/grpc/config/config.php
  src/Components/grpc/src/old-server/Error/DefaultGrpcErrorHandler.php
  src/Components/grpc/src/old-server/Error/GrpcErrorHandler.php
  src/Components/grpc/src/old-server/Server.php
Labels: optimization, 2.1, 2.0

#332 修复 Swoole BASE 模式只有一个进程时，没有输出监听端口信息
  src/Components/swoole/src/Listener/ServerStart.php
  src/Components/swoole/src/Server/Base.php
  src/Components/swoole/src/Server/ConnectionContext/Listener/AppInit.php
  src/Components/swoole/src/Server/Traits/TServerPortInfo.php
Labels: bug, 2.1, 2.0
