Repository imiphp/imi, pull requests merged in 2022-09, with the labels that each got.

#425 修复 Swoole RedisServerUtil 在集群模式时报错
  src/Components/swoole/src/Server/Util/RedisServerUtil.php
Labels: bug, 2.1

#427 修复未声明 Entity 注解的模型类报错
  src/Model/Meta.php
Labels: bug, 2.1, 2.0

#428 Docs: Typo fix
  doc/components/process/index.md
Labels: document

#431 修复执行定时任务时抛出 PDOException 无法正确捕获并二次抛出异常
  src/Cron/CronWorker.php
Labels: bug, 2.1, 2.0

#430 实现模型发号器，支持 UUID、雪花算法
  composer.json
  doc/components/orm/RDModel/definition.md
  src/Components/snowflake/src/Model/SnowflakeGenerator.php
  src/Components/snowflake/tests/Model/ArticleId.php
  src/Components/snowflake/tests/Unit/ModelGeneratorTest.php
  src/Components/snowflake/tests/config/config.php
  src/Model/Annotation/Id.php
  src/Model/IdGenerator/Contract/IIdGenerator.php
  src/Model/IdGenerator/UUIDGenerator.php
  src/Model/IdGenerator/UUIDGeneratorType.php
  src/Model/Meta.php
  src/Model/Model.php
  tests/unit/Component/Model/ArticleId.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#432 新增 RequestParam 注解
  doc/SUMMARY.md
  doc/components/httpserver/controller.md
  doc/components/httpserver/request.md
  doc/components/httpserver/response.md
  src/Bean/Annotation/AnnotationManager.php
  src/Bean/Annotation/Model/ClassAnnotation.php
  src/Bean/AnnotationParser.php
  src/Components/grpc/src/Middleware/ActionMiddleware.php
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Controller/IndexController.php
  src/Components/swoole/tests/unit/HttpServer/Tests/RequestTest.php
  src/Server/Http/Annotation/RequestParam.php
  src/Server/Http/Listener/HttpRouteInit.php
  src/Server/Http/Middleware/ActionMiddleware.php
Labels: enhancement, 2.1

#436 修复 Condition 注解的 callable 无法使用 ['$this', 'methodName'] 格式的值
  src/Validate/Annotation/Condition.php
Labels: bug, 2.1, 2.0
