Repository imiphp/imi, pull requests merged in 2023-06, with the labels that each got.

#529 修复查询构建器 `join` 方法传入 `$where` 参数的报错
  src/Db/Query/Join.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
Labels: bug, 2.1

#525 改进模型自动创建时间和更新时间
  src/Components/pgsql/src/Model/PgModel.php
  src/Components/pgsql/tests/Unit/Model/ModelTest.php
  src/Model/Model.php
  tests/unit/Component/Tests/ModelTest.php
Labels: optimization, 2.1

#532 修复事务检查时Db实例错误
  src/Db/Query/Query.php
Labels: bug, 2.1, 2.0

#531 支持绑定上传文件对象到控制器方法参数
  doc/base/version/2.0-2.1.md
  doc/components/httpserver/controller.md
  doc/components/httpserver/request.md
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Controller/IndexController.php
  src/Components/swoole/tests/unit/HttpServer/Tests/RequestTest.php
  src/Server/Http/Middleware/ActionMiddleware.php
Labels: enhancement, 2.1

#534 修复在 pgsql 字段默认值是表达式时，模型字段默认值不正确的问题
  .github/pgsql.sql
  src/Components/pgsql/src/Model/Cli/Model/ModelGenerate.php
  src/Components/pgsql/tests/Model/Base/MemberBase.php
Labels: bug, 2.1

#535 修复数据库驱动 Statement 类在未查询时也会更新最后插入ID的问题
  src/Components/pgsql/src/Db/Drivers/Swoole/Statement.php
  src/Components/pgsql/src/Db/Drivers/SwooleNew/Driver.php
  src/Components/pgsql/src/Db/Drivers/SwooleNew/Statement.php
  src/Db/Drivers/TPdoDriver.php
  src/Db/Drivers/TPdoStatement.php
Labels: bug, 2.1

#533 数据库查询构建器支持全文搜索（MySQL+PostgreSQL）
  doc/components/db/index.md
  src/Components/pgsql/src/Db/Query/FullText/PgsqlFullTextOptions.php
  src/Components/pgsql/src/Db/Query/FullText/TsQuery.php
  src/Components/pgsql/src/Db/Query/FullText/TsRank.php
  src/Components/pgsql/src/Db/Query/PgsqlQuery.php
  src/Components/pgsql/tests/Unit/Db/QueryCurdBaseTest.php
  src/Db/Mysql/Query/FullText/MysqlFullTextOptions.php
  src/Db/Mysql/Query/FullText/SearchModifier.php
  src/Db/Mysql/Query/MysqlQuery.php
  src/Db/Query/FullText/BaseFullTextOptions.php
  src/Db/Query/Interfaces/IFullTextOptions.php
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Interfaces/IWhereFullText.php
  src/Db/Query/Query.php
  src/Db/Query/Where/BaseWhere.php
  src/Db/Query/Where/Where.php
  src/Db/Query/Where/WhereBrackets.php
  src/Db/Query/Where/WhereFullText.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
Labels: enhancement, 2.1

#539 修复覆盖率测试和偶发测试失败
  .github/workflows/codecov.yml
  src/Components/pgsql/tests/Unit/Model/ModelTest.php
  src/Components/swoole/tests/unit/HttpServer/Tests/ProcessTest.php
  src/Components/swoole/tests/unit/WebSocketServer/Tests/ServerUtilTest.php
  src/Components/swoole/tests/unit/WebSocketServerWithAmqpRouteServerUtil/Tests/ServerUtilTest.php
  src/Components/swoole/tests/unit/WebSocketServerWithAmqpServerUtil/Tests/ServerUtilTest.php
  src/Components/swoole/tests/unit/WebSocketServerWithRedisServerUtil/Tests/ServerUtilTest.php
  src/Components/workerman-gateway/tests/bootstrap.php
  tests/unit/Component/Tests/ModelTest.php
Labels: bug, 2.1

#538 修复 AnnotationManager 获取注解方法，传入 $onlyFirst=true 找不到注解时特定情况不返回 null
  src/Bean/Annotation/AnnotationManager.php
  src/Model/RedisModel.php
  src/Model/Tree/TTreeModel.php
Labels: bug, 2.1

#540 修复扫描BUG
  composer.json
  src/Bean/Annotation/Model/AnnotationRelation.php
  src/Bean/AnnotationLoader.php
  src/Bean/AnnotationParser.php
  src/Components/fpm/tests/HttpServer/bin/start.sh
  tests/unit/Component/Tests/Db/TransactionTest.php
  tests/unit/Component/config/config.php
Labels: bug, 2.1, 2.0

#541 改进服务相关
  doc/core/processNameManager.md
  src/Components/swoole/src/Server/Cli/Server.php
  src/Components/workerman-gateway/tests/bootstrap.php
  src/Components/workerman/src/Listener/OnWorkerStart.php
  src/Components/workerman/src/Process/ProcessManager.php
  src/Components/workerman/src/Server/Cli/Server.php
  src/Components/workerman/src/Server/WorkermanServerWorker.php
  src/Components/workerman/src/Util/Imi.php
Labels: bug, enhancement, optimization, 2.1

#537 生成模型相关改进
  doc/dev/generate/model.md
  src/Model/Cli/Model/Event/Param/AfterGenerateModel.php
  src/Model/Cli/Model/Event/Param/AfterGenerateModels.php
  src/Model/Cli/Model/Event/Param/BeforeGenerateModel.php
  src/Model/Cli/Model/Event/Param/BeforeGenerateModels.php
  src/Model/Cli/Model/Event/Param/TGenerateModel.php
  src/Model/Cli/Model/ModelGenerate.php
  src/Model/Cli/Model/base-template.tpl
Labels: bug, enhancement, 2.1

#543 优化代码
  config/config.php
  src/Components/fpm/src/FpmApp.php
  src/Components/workerman-gateway/tests/unit/AppServer/bin/start-workerman.ps1
Labels: optimization, 2.1

#545 修复 SWOOLE_PROCESS 模式获取 master 进程 pid
  phpstan.neon
  src/Components/swoole/src/Cron/Scheduler.php
  src/Components/swoole/src/Process/ProcessManager.php
  src/Components/swoole/src/Server/Base.php
  src/Components/swoole/src/Server/Traits/TServerPortInfo.php
  src/Components/swoole/src/Task/TaskManager.php
  src/Components/swoole/src/Util/Swoole.php
  src/Components/swoole/src/Worker/SwooleWorkerHandler.php
  src/Server/ServerManager.php
Labels: bug, 2.1, 2.0

#546 修复事件名称是动态设定时，仅触发一次的事件被执行后，有残留数据导致内存泄漏
  src/Db/Transaction/Transaction.php
  src/Event/TEvent.php
  tests/unit/Component/Tests/Db/TransactionTest.php
Labels: bug, 2.1, 2.0

#547 优化软删除查询构建器及时释放内存（非泄露）
  doc/components/db/index.md
  src/Db/Query/Where/WhereBrackets.php
  src/Model/SoftDelete/Traits/TSoftDelete.php
Labels: optimization, 2.1

#548 修复事务嵌套时，事件触发不正确
  src/Db/Transaction/Transaction.php
  tests/unit/Component/Db/Classes/TestTransaction.php
  tests/unit/Component/Tests/Db/TransactionTest.php
Labels: bug, 2.1

#542 支持 MySQL 高性能分页查询（大表分页类）
  doc/components/db/index.md
  src/Db/Mysql/Query/Pagination/BigTablePagination.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
Labels: enhancement, 2.1

#550 修复可能存在的定时器未捕获错误
  src/Components/amqp/src/Swoole/AMQPSwooleConnection.php
  src/Components/mqtt/src/Client/MQTTClient.php
  src/Components/pgsql/tests/PHPUnitHook.php
  src/Components/swoole/src/HotUpdate/HotUpdateProcess.php
  src/Components/swoole/src/Listener/WorkerExit.php
  src/Components/swoole/src/Lock/Handler/Atomic.php
  src/Components/swoole/src/Pool/BaseAsyncPool.php
  src/Components/swoole/src/Server/ConnectionContext/StoreHandler/MemoryTable.php
  src/Components/swoole/src/Server/Http/Middleware/ExecuteTimeoutMiddleware.php
  src/Server/Http/Route/HttpRoute.php
Labels: bug, 2.1, 2.0
