Repository imiphp/imi, pull requests merged in 2023-05, with the labels that each got.

#507 模型查询构建器支持定义表别名
  doc/base/version/2.0-2.1.md
  doc/components/orm/RDModel.md
  src/Components/pgsql/src/Model/PgModel.php
  src/Components/pgsql/tests/Unit/Model/ModelTest.php
  src/Db/Query/Interfaces/IQuery.php
  src/Model/Model.php
  src/Model/SoftDelete/Traits/TSoftDelete.php
  tests/unit/Component/Tests/ModelTest.php
Labels: enhancement, 2.1

#509 修复部分场景下会出现报错：Typed property xxx must not be accessed before initialization
  src/Components/grpc/src/Proxy/Http/GrpcHttpProxy.php
  src/Components/mqtt/src/imi/Server/MQTT/DataParser/MQTTDataParser.php
  src/Server/Http/Controller/HttpController.php
  src/Server/TcpServer/Controller/TcpController.php
  src/Server/UdpServer/Controller/UdpController.php
  src/Server/WebSocket/Controller/WebSocketController.php
Labels: bug, 2.1, 2.0

#511 Imi\Util\Random 新增 float() 和 bytes() 方法
  doc/base/version/2.0-2.1.md
  doc/utils/Random.md
  src/Server/Session/SessionManager.php
  src/Util/Random.php
  tests/unit/Component/Tests/Util/RandomTest.php
Labels: enhancement, optimization, 2.1

#512 修复 Model::query() 查询动态指定不存在的字段，序列化时不返回该字段
  src/Model/ModelQueryResult.php
  tests/unit/Component/Tests/ModelTest.php
Labels: optimization, 2.1

#514 解决开发依赖目录软链产生死循环问题
  dev/PHPStan/FileFinder.php
  phpstan-components.neon
  phpstan.neon
  src/Components/amqp/dev/Dev.php
  src/Components/grpc/dev/Dev.php
  src/Components/hprose/dev/Dev.php
  src/Components/kafka/dev/Dev.php
  src/Components/mqtt/dev/Dev.php
  src/Components/pgsql/dev/Dev.php
  src/Components/queue/dev/Dev.php
  src/Components/rpc/dev/Dev.php
  src/Components/smarty/dev/Dev.php
  src/Components/swoole/dev/Dev.php
  src/Components/workerman-gateway/dev/Dev.php
Labels: bug, 2.1

#513 新增使用 Protobuf 的 gRPC HTTP 网关客户端
  doc/base/version/2.0-2.1.md
  doc/components/rpc/grpc-proxy.md
  src/Components/grpc/example/GrpcServer/Controller/TestServiceController.php
  src/Components/grpc/src/Proxy/Http/GrpcHttpClient.php
  src/Components/grpc/src/Proxy/Http/GrpcHttpProxy.php
  src/Components/grpc/tests/Grpc/GrpcTest.php
Labels: enhancement, 2.1

#515 启用核心覆盖率测试
  .github/workflows/codecov.yml
  README.md
  src/Components/amqp/tests/phpunit.xml
  src/Components/fpm/tests/phpunit.xml
  src/Components/grpc/tests/phpunit.xml
  src/Components/jwt/tests/phpunit.xml
  src/Components/kafka/tests/phpunit.xml
  src/Components/mqtt/tests/phpunit.xml
  src/Components/pgsql/tests/phpunit.xml
  src/Components/queue/tests/phpunit.xml
  src/Components/roadrunner/tests/phpunit.xml
  src/Components/smarty/tests/phpunit.xml
  src/Components/snowflake/tests/phpunit.xml
  src/Components/swoole/tests/phpunit.xml
  src/Components/workerman-gateway/tests/phpunit.xml
  src/Components/workerman/tests/phpunit.xml
  tests/phpunit.xml
Labels: enhancement, 2.1

#523 修复非 POST 请求使用 getParsedBody() 无法获取 JSON 反序列化数据
  src/Util/Http/ServerRequest.php
  tests/unit/Component/Tests/Util/Http/ServerRequestTest.php
Labels: bug, 2.1, 2.0

#524 支持 PostgreSQL 生成模型配置 bean 和 incrUpdate 参数
  src/Components/pgsql/src/Model/Cli/Model/ModelGenerate.php
  src/Components/pgsql/src/Model/Cli/Model/base-template.tpl
  src/Components/pgsql/src/Model/PgModel.php
  src/Components/pgsql/tests/Model/Base/ArticleBase.php
  src/Components/pgsql/tests/Model/Base/MemberBase.php
  src/Components/pgsql/tests/Model/Base/PerformanceBase.php
  src/Components/pgsql/tests/Model/Base/TestJsonBase.php
  src/Components/pgsql/tests/Model/Base/TestSoftDeleteBase.php
  src/Components/pgsql/tests/Model/Base/TreeBase.php
  src/Components/pgsql/tests/Model/Base/UpdateTimeBase.php
  src/Components/pgsql/tests/Model/Base/VirtualColumnBase.php
  src/Model/SoftDelete/Traits/TSoftDelete.php
Labels: enhancement, 2.1

#520 增强：Imi\Lock\Lock 类中的相关方法增加 $lockId 参数
  doc/components/lock/index.md
  src/Components/swoole/tests/unit/Component/Tests/LockAtomicTest.php
  src/Lock/Handler/Redis.php
  src/Lock/Lock.php
  tests/unit/Component/Tests/BaseLockTest.php
  tests/unit/Component/Tests/LockRedisTest.php
Labels: enhancement, 2.1

#528 数据库迁移组件文档中,生成同步命令由migration/patch 修改migration/dump
  doc/components/orm/migration.md
Labels: document

#526 修复 Swoole BASE 模式下获取 masterPid 错误
  src/Components/swoole/src/Worker/SwooleWorkerHandler.php
Labels: bug, 2.1, 2.0
