Repository imiphp/imi, pull requests merged in 2023-04, with the labels that each got.

#487 修复 setFieldInc、setFieldDec
  doc/components/db/index.md
  src/Components/pgsql/tests/Unit/Db/QueryCurdBaseTest.php
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: bug, 2.1

#488 增加环境变量 IMI_SCAN_STATISTICS，支持关闭输出扫描阶段的日志
  doc/SUMMARY.md
  doc/container/roadrunner.md
  doc/core/env.md
  src/Bean/Scanner.php
Labels: enhancement, 2.1

#491 修复 imi-phar 与 php-cs-fixer 的兼容性
  .github/workflows/phpstan.yml
  phpstan-components.neon
  src/Components/phar/composer.json
  src/Components/phar/config/config.php
  src/Components/phar/phar_init.php
  src/Components/phar/src/Ignore/PharHandler2.php
  src/Components/phar/src/Ignore/PharHandler3.php
  src/Components/phar/src/PharBuildCommand.php
  src/Components/phar/src/PharHandler.php
  src/Components/phar/src/PharService.php
  src/Components/phar/src/TPharHandler.php
  src/Components/phar/tests/project/ApiServer/Controller/IndexController.php
  src/Components/phar/tests/project/composer.json
  src/Components/phar/tests/run-tests.php
Labels: optimization, 2.1

#492 修复模型查询时手动指定字段，查询结果序列化可能会出现数字字段名
  doc/components/orm/RDModel.md
  doc/components/orm/RDModel/definition.md
  src/Model/ModelQueryResult.php
  tests/unit/Component/Model/Member.php
  tests/unit/Component/Tests/ModelTest.php
Labels: bug, 2.1

#494 修复 MySQL 的 json 操作时，无法用双引号把字段名括起来
  src/Components/swoole/tests/unit/Component/Tests/Db/Swoole/QueryCurdTest.php
  src/Db/Mysql/Query/Builder/UpdateBuilder.php
  src/Db/Mysql/Query/MysqlQuery.php
  tests/unit/Component/Tests/Db/Mysqli/QueryCurdTest.php
  tests/unit/Component/Tests/Db/Pdo/QueryCurdTest.php
  tests/unit/Component/Tests/Db/QueryCurdBaseTest.php
Labels: bug, 2.1, 2.0

#500 优化消息队列中使用 Redis 连接，使用完即释放
  src/Components/amqp/src/Queue/AMQPQueueDriverHandler.php
  src/Components/queue/src/Driver/RedisQueueDriver.php
  src/Components/queue/src/Driver/RedisStreamQueueDriver.php
  src/Components/swoole/src/Pool/BaseAsyncPool.php
  src/Pool/PoolManager.php
Labels: optimization, 2.1

#502 修复连接池心跳在 Swoole 消息队列消费进程中不执行
  src/Components/queue/src/Process/SwooleQueueConsumerProcess.php
  src/Components/swoole/src/SwooleApp.php
Labels: bug, 2.1

#503 异步执行新增 Defer、DeferAsync 注解
  doc/base/version/2.0-2.1.md
  doc/components/async/index.md
  src/Async/Annotation/Defer.php
  src/Async/Annotation/DeferAsync.php
  src/Async/Aop/AsyncAop.php
  src/Async/Async.php
  src/Async/Contract/IAsyncHandler.php
  src/Async/Sync/SyncHandler.php
  src/Components/swoole/src/Async/SwooleHandler.php
  src/Components/swoole/tests/unit/Component/Async/AsyncTester.php
  src/Components/swoole/tests/unit/Component/Tests/AsyncTest.php
  tests/unit/Component/Async/AsyncTester.php
  tests/unit/Component/Tests/AsyncTest.php
Labels: enhancement, 2.1

#504 更新 monolog 版本
  composer.json
  src/Log/MonoLogger.php
Labels: optimization, 2.1

#506 支持优雅的 SSE 服务端推送功能
  doc/SUMMARY.md
  doc/base/version/2.0-2.1.md
  doc/components/httpserver/sse.md
  src/Components/fpm/src/Http/Message/FpmEmitHandler.php
  src/Components/fpm/src/Http/Message/FpmResponse.php
  src/Components/fpm/tests/HttpServer/Tests/ResponseTest.php
  src/Components/fpm/tests/Web/Controller/IndexController.php
  src/Components/fpm/tests/Web/Middleware/PoweredBy.php
  src/Components/grpc/example/GrpcServer/Middleware/PoweredBy.php
  src/Components/phar/tests/project/ApiServer/Middleware/PoweredBy.php
  src/Components/roadrunner/tests/unit/HttpServer/Middleware/PoweredBy.php
  src/Components/smarty/example/MainServer/Middleware/PoweredBy.php
  src/Components/swoole/src/Http/Message/SwooleEmitHandler.php
  src/Components/swoole/src/Http/Message/SwooleResponse.php
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Controller/IndexController.php
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Middleware/PoweredBy.php
  src/Components/swoole/tests/unit/HttpServer/Tests/ResponseTest.php
  src/Components/workerman-gateway/tests/unit/AppServer/ApiServer/Middleware/PoweredBy.php
  src/Components/workerman/src/Http/Message/WorkermanEmitHandler.php
  src/Components/workerman/src/Http/Message/WorkermanResponse.php
  src/Components/workerman/tests/unit/AppServer/ApiServer/Controller/IndexController.php
  src/Components/workerman/tests/unit/AppServer/ApiServer/Middleware/PoweredBy.php
  src/Components/workerman/tests/unit/AppServer/Tests/Http/ResponseTest.php
  src/Server/Http/Message/Contract/IHttpResponse.php
  src/Server/Http/Message/Emitter/Contract/BaseEmitter.php
  src/Server/Http/Message/Emitter/Contract/IResponseBodyEmitter.php
  src/Server/Http/Message/Emitter/Handler/IEmitHandler.php
  src/Server/Http/Message/Emitter/SseEmitter.php
  src/Server/Http/Message/Emitter/SseMessageEvent.php
  src/Server/Http/Message/Proxy/ResponseProxy.php
  src/Server/Http/Message/Proxy/ResponseProxyObject.php
  src/Server/Http/Message/Response.php
  src/Server/Http/Middleware/RouteMiddleware.php
  src/Util/Stream/MemoryStream.php
  tests/unit/Component/Tests/Server/Http/SseMessageEventTest.php
Labels: enhancement, 2.1
