Repository imiphp/imi, pull requests merged in 2023-11, with the labels that each got.

#628 修复一些注解问题
  doc/components/udpServer/controller.md
  src/Bean/Annotation/Base.php
  src/Validate/Annotation/Scene.php
  tests/unit/Component/Model/TestRedisHashObjectColumnTypeModel.php
Labels: bug, document, 2.1

#632 修复一些问题
  src/Bean/Annotation/Model/ClassAnnotation.php
  src/Components/grpc/src/Enum/GrpcStatus.php
  src/Components/grpc/src/Parser.php
  src/Components/swoole/src/Cron/Listener/WorkerPartPipeMessage.php
Labels: bug, 2.1

#634 修复 PostgreSQL replace() 没有更新字段值
  src/Components/pgsql/src/Db/Query/Builder/InsertBuilder.php
  src/Components/pgsql/src/Db/Query/Builder/ReplaceBuilder.php
  src/Components/pgsql/tests/Unit/Db/QueryCurdBaseTest.php
  src/Components/pgsql/tests/Unit/Model/ModelTest.php
  tests/unit/Component/Tests/Db/DbBaseTest.php
  tests/unit/Component/Tests/ModelTest.php
Labels: bug, 2.1

#635 [3.0] 切换 CI 环境使用镜像并补充测试缓存
  .github/actions/ci-prepare/action.yml
  .github/docker-compose.yml
  .github/workflows/ci.yml
  .github/workflows/codecov.yml
  .github/workflows/phpcs.yml
  .github/workflows/phpstan.yml
  .github/workflows/rector.yml
  dev/bootstrap.php
  dev/phpstan.sh
  phpstan-baseline/component-baseline.php
  phpstan.neon
Labels: 3.0

#637 修复临时设置服务器到请求上下文后的恢复
  src/Components/swoole/src/Listener/AfterWorkerStart.php
  src/Components/swoole/src/Server/ConnectionContext/Listener/AppInit.php
  src/Components/swoole/src/Server/Listener/OnCloseByFlagRequest.php
  src/Components/swoole/src/Server/Listener/OnExistsRequest.php
  src/Components/swoole/src/Server/Listener/OnSendRawByFlagRequest.php
  src/Components/swoole/src/Server/Listener/OnSendRawToAllRequest.php
  src/Components/swoole/src/Server/Listener/OnSendToClientIdsRequest.php
  src/Components/swoole/src/Server/Listener/OnSendToGroupsRequest.php
  src/Components/swoole/src/Server/Util/Amqp/AmqpServerConsumer.php
  src/Components/workerman/src/Server/Listener/OnCloseByFlagRequest.php
  src/Components/workerman/src/Server/Listener/OnSendRawByFlagRequest.php
  src/Components/workerman/src/Server/Listener/OnSendRawToAllRequest.php
  src/Components/workerman/src/Server/Listener/OnSendRawToGroupRequest.php
  src/Server/Contract/BaseServer.php
  src/Server/Http/Listener/HttpRouteInit.php
  src/Server/TcpServer/Listener/TcpRouteInit.php
  src/Server/UdpServer/Listener/UdpRouteInit.php
  src/Server/WebSocket/Listener/WSRouteInit.php
Labels: bug, 2.1

#639 修复 Windows workerman-gateway 有时候测试失败
  .github/print-logs.php
  src/Components/workerman-gateway/tests/bootstrap.php
  src/Components/workerman-gateway/tests/unit/AppServer/bin/start-server.ps1
  src/Components/workerman-gateway/tests/unit/AppServer/bin/start-workerman.ps1
Labels: bug, 2.1

#640 [3.0] 修复Win测试稳定性并优化测试缓存
  .github/workflows/ci.yml
  src/Components/workerman-gateway/tests/bootstrap.php
Labels: 3.0

#642 修复 ConnectionContextStore 初始化
  src/Components/swoole/src/Server/ConnectionContext/Listener/AppInit.php
  src/Server/ConnectionContext/StoreHandler.php
Labels: bug, 2.1

#641 v2.1 中已经标记为 deprecated 的在 v3.0 废弃
  doc/base/version/2.1-3.0.md
  doc/components/db/config.md
  doc/components/db/index.md
  doc/components/db/mysql.md
  doc/components/httpserver/request.md
  doc/components/httpserver/validation.md
  doc/components/orm/RDModel.md
  doc/utils/functions.md
  src/Cache/Handler/Base.php
  src/Cache/Handler/File.php
  src/Cache/Handler/Memory.php
  src/Cache/Handler/Redis.php
  src/Cache/Handler/RedisHash.php
  src/Cache/Handler/RequestContext.php
  src/Components/amqp/src/Pool/AMQPCoroutinePool.php
  src/Components/amqp/src/Pool/AMQPSyncPool.php
  src/Components/grpc/composer.json
  src/Components/grpc/src/old-server/Error/DefaultGrpcErrorHandler.php
  src/Components/grpc/src/old-server/Error/GrpcErrorHandler.php
  src/Components/grpc/src/old-server/Server.php
  src/Components/kafka/src/Pool/KafkaCoroutinePool.php
  src/Components/kafka/src/Pool/KafkaSyncPool.php
  src/Components/rpc/src/Client/Pool/RpcClientCoroutinePool.php
  src/Components/rpc/src/Client/Pool/RpcClientSyncPool.php
  src/Components/shared-memory/src/Pool/ClientPool.php
  src/Components/swoole/src/Db/Driver/Swoole/Driver.php
  src/Components/swoole/src/Db/Driver/Swoole/Statement.php
  src/Components/swoole/src/Db/Pool/CoroutineDbPool.php
  src/Components/swoole/tests/phpunit.xml
  src/Components/swoole/tests/unit/Component/Performance/SwooleMysqlDbTest.php
  src/Components/swoole/tests/unit/Component/Tests/Db/Swoole/DbTest.php
  src/Components/swoole/tests/unit/Component/Tests/Db/Swoole/QueryCurdTest.php
  src/Components/swoole/tests/unit/Component/config/config.php
  src/Components/swoole/tests/unit/HttpServer/ApiServer/Controller/IndexController.php
  src/Components/swoole/tests/unit/HttpServer/Tests/RequestTest.php
  src/Db/Pool/SyncDbPool.php
  src/Db/Query/Interfaces/IQuery.php
  src/Db/Query/Query.php
  src/HttpValidate/Annotation/ExtractData.php
  src/Log/ErrorLog.php
  src/Model/Annotation/DDL.php
  src/Model/Traits/TJsonValue.php
  src/Model/Traits/TListValue.php
  src/Model/Traits/TModelQuery.php
  src/Model/Traits/TSetValue.php
  src/Pool/BasePool.php
  src/Pool/ResourceConfigMode.php
  src/Redis/Traits/TRedisPool.php
  src/Server/Http/Annotation/ExtractData.php
  src/Server/Http/Listener/HttpRouteInit.php
  src/Util/ArrayData.php
  src/Util/DateTime.php
  src/functions.php
  tests/unit/Component/Tests/EnvTest.php
Labels: 3.0

#645 优化 ArrayUtil::isAssoc
  src/Util/ArrayUtil.php
Labels: 3.0

#647 [3.0] 优化每日测试
  .github/docker-compose.yml
  .github/workflows/daily-test.yml
Labels: 3.0

#646 PHP 原生枚举深度支持
  phpstan.neon
  src/Bean/BeanFactory.php
  src/Bean/BeanProxy.php
  src/Bean/Container.php
  src/Components/grpc/composer.json
  src/Util/EnumUtil.php
  src/Validate/ValidatorHelper.php
  tests/unit/Component/Bean/EnumBean.php
  tests/unit/Component/Enum/TestEnumBean.php
  tests/unit/Component/Enum/TestEnumBeanBacked.php
  tests/unit/Component/Tests/BeanTest.php
  tests/unit/Component/Tests/Util/EnumTest.php
  tests/unit/Component/Tests/ValidatorHelperTest.php
  tests/unit/Component/config/config.php
Labels: enhancement, 3.0, 2.1

#649 强类型改为注释类型，避免未安装对应扩展运行时报类型错误
  src/Components/pgsql/src/Db/Drivers/Swoole/Driver.php
  src/Components/pgsql/src/Db/Drivers/SwooleNew/Driver.php
  src/Db/Drivers/TPdoDriver.php
  src/Db/Mysql/Drivers/Mysqli/Driver.php
Labels: 3.0

#650 [3.0] 移除旧的枚举，独立旧枚举组件
  doc/components/struct/enum.md
  src/Enum/Annotation/EnumItem.php
  src/Enum/Annotation/Parser/EnumParser.php
  src/Enum/BaseEnum.php
  src/Enum/EnumManager.php
  src/Enum/Listener/BuildRuntimeListener.php
  src/Enum/Listener/LoadRuntimeListener.php
  src/Main.php
  tests/unit/Component/Annotation/TestAnnotation.php
  tests/unit/Component/Enum/TestEnum.php
  tests/unit/Component/Inherit/ParentClass.php
  tests/unit/Component/Tests/Annotation/AnnotationTest.php
  tests/unit/Component/Tests/EnumTest.php
  tests/unit/Component/Tests/InheritTest.php
  tests/unit/Component/Tests/ValidatorAnnotationTest.php
  tests/unit/Component/Tests/ValidatorHelperTest.php
  tests/unit/Component/Validate/Classes/TestAutoConstructValidator.php
  tests/unit/Component/Validate/Classes/TestValidator.php
Labels: 3.0

#644 [3.0] Bean 类默认禁止递归
  doc/base/version/2.1-3.0.md
  doc/core/container.md
  src/Bean/Annotation/Bean.php
  src/Bean/Container.php
  src/Components/amqp/src/Queue/AMQPQueueDriver.php
  src/Components/grpc/src/Middleware/ActionMiddleware.php
  src/Components/grpc/src/Proxy/Http/GrpcHttpProxy.php
  src/Components/grpc/src/Util/GrpcInterfaceManager.php
  src/Components/jwt/src/Bean/JWT.php
  src/Components/mqtt/src/imi/Server/MQTT/DataParser/MQTTDataParser.php
  src/Components/queue/src/Driver/RedisQueueDriver.php
  src/Components/queue/src/Driver/RedisStreamQueueDriver.php
  src/Components/swoole-tracker/src/TCP/Middleware/SwooleTrackerMiddleware.php
  src/Components/swoole-tracker/src/UDP/Middleware/SwooleTrackerMiddleware.php
  src/Components/swoole-tracker/src/WebSocket/Middleware/SwooleTrackerMiddleware.php
  src/Components/swoole/src/Cron/CronManager.php
  src/Components/swoole/src/Cron/Scheduler.php
  src/Components/swoole/src/Server/ConnectionContext/StoreHandler/Amqp.php
  src/Components/swoole/src/Server/ConnectionContext/StoreHandler/MemoryTable.php
  src/Components/swoole/src/Server/Util/AmqpServerUtil.php
  src/Components/swoole/src/Server/Util/LocalServerUtil.php
  src/Components/swoole/src/Server/Util/RedisServerUtil.php
  src/Cron/CronManager.php
  src/Db/Event/DbQueryLog.php
  src/Server/ConnectionContext/StoreHandler.php
  src/Server/ConnectionContext/StoreHandler/Local.php
  src/Server/ConnectionContext/StoreHandler/Redis.php
  src/Server/Group/Handler/Redis.php
  src/Server/Http/Dispatcher.php
  src/Server/Http/Error/HttpNotFoundHandler.php
  src/Server/Http/Message/Proxy/RequestProxyObject.php
  src/Server/Http/Message/Proxy/ResponseProxyObject.php
  src/Server/Http/Middleware/ActionMiddleware.php
  src/Server/Http/Middleware/RouteMiddleware.php
  src/Server/Http/Route/HttpRoute.php
  src/Server/Session/Handler/File.php
  src/Server/Session/Handler/Redis.php
  src/Server/Session/SessionConfig.php
  src/Server/Session/SessionCookie.php
  src/Server/Session/SessionManager.php
  src/Server/TcpServer/Dispatcher.php
  src/Server/TcpServer/Message/Proxy/ReceiveDataProxy.php
  src/Server/TcpServer/Middleware/RouteMiddleware.php
  src/Server/UdpServer/Dispatcher.php
  src/Server/UdpServer/Message/Proxy/PacketDataProxy.php
  src/Server/UdpServer/Middleware/RouteMiddleware.php
  src/Server/View/Handler/Html.php
  src/Server/View/View.php
  src/Server/WebSocket/Dispatcher.php
  src/Server/WebSocket/Message/Proxy/FrameProxy.php
  src/Server/WebSocket/Middleware/RouteMiddleware.php
  src/Server/WebSocket/Route/WSRoute.php
Labels: 3.0

#657 修复 Windows PHP 8.2 测试
  .github/workflows/ci.yml
Labels: 2.1
